In [1]:
import gymnasium as gym
import seaborn as sns
import os
from collections import deque, Counter, namedtuple, defaultdict
import random
from matplotlib import pyplot as plt
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=UserWarning)
import torch
from torch import nn
import torch.nn.functional as F
import math
from itertools import count
from tqdm import tqdm
import numpy as np
import time

#Setting up matplotlib for live update the traiing progress
import matplotlib
is_ipython = 'inline' in matplotlib.get_backend()
if is_ipython:
    from IPython import display

https://www.gymlibrary.dev/content/vectorising/

In [12]:
envs = gym.vector.make('CartPole-v1', num_envs = 3)
state, info = envs.reset()

print(state.shape)

print(envs.observation_space)

print(envs.action_space)

(3, 4)
Box([[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]
 [-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]
 [-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]], [[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
 [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
 [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]], (3, 4), float32)
MultiDiscrete([2 2 2])


In [3]:
print(state)

[[-0.03351751 -0.04042975  0.00314499 -0.03789013]
 [-0.03961974  0.04216014  0.03995275  0.03205689]
 [-0.02411309 -0.04103078  0.00922917  0.03424837]]


In [8]:
actions = np.array([1,0,1])
states, rewards, terminated, truncated, infos = envs.step(actions) 

print(states)
print(rewards)
print(terminated)
print(truncated)
print(infos)

[[ 0.0489324   0.24395245  0.01623587 -0.28193223]
 [-0.02288923 -0.19724691 -0.00410903  0.3023964 ]
 [ 0.03979137  0.1981668  -0.00971662 -0.3211251 ]]
[1. 1. 1.]
[False False False]
[False False False]
{}


/Users/jamesnguyen/anaconda3/envs/torch/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


# Asynchronous envs

In [ ]:
envs = gym.vector.AsyncVectorEnv([
    lambda: gym.make('CartPole-v1'),
    lambda: gym.make('CartPole-v1'),
    lambda: gym.make('CartPole-v1'),
])